numbers = list(range(6))
print('The first three items in the list are:')
print(numbers[:3])
print('Three items from the middle of the list are:')
print(numbers[1:4])
print('The last three items in the list are:')
print(numbers[-3:])